# Generated by Django 3.1 on 2021-11-24 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartItrm',
            new_name='CartItem',
        ),
    ]
